// Mocks generated by Mockito 5.4.4 from annotations
// in coordimate/test/meeting_info_page_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i12;

import 'package:coordimate/controllers/auth_controller.dart' as _i9;
import 'package:coordimate/controllers/meeting_controller.dart' as _i5;
import 'package:coordimate/models/agenda_point.dart' as _i8;
import 'package:coordimate/models/meeting.dart' as _i2;
import 'package:google_sign_in/google_sign_in.dart' as _i4;
import 'package:googleapis/calendar/v3.dart' as _i11;
import 'package:googleapis_auth/googleapis_auth.dart' as _i10;
import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMeetingDetails_0 extends _i1.SmartFake
    implements _i2.MeetingDetails {
  _FakeMeetingDetails_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClient_1 extends _i1.SmartFake implements _i3.Client {
  _FakeClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoogleSignIn_2 extends _i1.SmartFake implements _i4.GoogleSignIn {
  _FakeGoogleSignIn_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MeetingController].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeetingController extends _i1.Mock implements _i5.MeetingController {
  MockMeetingController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.MeetingDetails> fetchMeetingDetails(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMeetingDetails,
          [id],
        ),
        returnValue: _i6.Future<_i2.MeetingDetails>.value(_FakeMeetingDetails_0(
          this,
          Invocation.method(
            #fetchMeetingDetails,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.MeetingDetails>);

  @override
  _i6.Future<String> fetchMeetingSummary(dynamic id) => (super.noSuchMethod(
        Invocation.method(
          #fetchMeetingSummary,
          [id],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #fetchMeetingSummary,
            [id],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<bool> finishMeeting(dynamic id) => (super.noSuchMethod(
        Invocation.method(
          #finishMeeting,
          [id],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i2.MeetingStatus> answerInvitation(
    bool? accept,
    dynamic id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #answerInvitation,
          [
            accept,
            id,
          ],
        ),
        returnValue:
            _i6.Future<_i2.MeetingStatus>.value(_i2.MeetingStatus.declined),
      ) as _i6.Future<_i2.MeetingStatus>);

  @override
  _i6.Future<List<_i2.MeetingTileModel>> fetchArchivedMeetings() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchArchivedMeetings,
          [],
        ),
        returnValue: _i6.Future<List<_i2.MeetingTileModel>>.value(
            <_i2.MeetingTileModel>[]),
      ) as _i6.Future<List<_i2.MeetingTileModel>>);

  @override
  _i6.Future<void> saveSummary(
    dynamic id,
    dynamic summaryText,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSummary,
          [
            id,
            summaryText,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.AgendaPoint>> getAgendaPoints(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAgendaPoints,
          [id],
        ),
        returnValue:
            _i6.Future<List<_i8.AgendaPoint>>.value(<_i8.AgendaPoint>[]),
      ) as _i6.Future<List<_i8.AgendaPoint>>);

  @override
  _i6.Future<void> createAgendaPoint(
    dynamic id,
    String? text,
    int? level,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAgendaPoint,
          [
            id,
            text,
            level,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAgendaPoint(
    dynamic id,
    int? index,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAgendaPoint,
          [
            id,
            index,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateAgenda(
    dynamic id,
    dynamic agenda,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAgenda,
          [
            id,
            agenda,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.MeetingTileModel>> fetchMeetings() => (super.noSuchMethod(
        Invocation.method(
          #fetchMeetings,
          [],
        ),
        returnValue: _i6.Future<List<_i2.MeetingTileModel>>.value(
            <_i2.MeetingTileModel>[]),
      ) as _i6.Future<List<_i2.MeetingTileModel>>);

  @override
  _i6.Future<void> createMeeting(
    String? title,
    String? start,
    int? length,
    String? description,
    String? groupId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMeeting,
          [
            title,
            start,
            length,
            description,
            groupId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateMeetingTime(
    String? meetingId,
    String? start,
    int? duration,
    String? googleEventId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMeetingTime,
          [
            meetingId,
            start,
            duration,
            googleEventId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteMeeting(
    String? meetingId,
    String? googleEventId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMeeting,
          [
            meetingId,
            googleEventId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String> suggestMeetingLocation(String? meetingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #suggestMeetingLocation,
          [meetingId],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #suggestMeetingLocation,
            [meetingId],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> updateMeetingLink(
    String? id,
    String? link,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMeetingLink,
          [
            id,
            link,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [AuthorizationController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthorizationController extends _i1.Mock
    implements _i9.AuthorizationController {
  MockAuthorizationController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Client get plainClient => (super.noSuchMethod(
        Invocation.getter(#plainClient),
        returnValue: _FakeClient_1(
          this,
          Invocation.getter(#plainClient),
        ),
      ) as _i3.Client);

  @override
  _i4.GoogleSignIn get googleSignIn => (super.noSuchMethod(
        Invocation.getter(#googleSignIn),
        returnValue: _FakeGoogleSignIn_2(
          this,
          Invocation.getter(#googleSignIn),
        ),
      ) as _i4.GoogleSignIn);

  @override
  set googleAuthClient(_i10.AuthClient? _googleAuthClient) =>
      super.noSuchMethod(
        Invocation.setter(
          #googleAuthClient,
          _googleAuthClient,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set calApi(_i11.CalendarApi? _calApi) => super.noSuchMethod(
        Invocation.setter(
          #calApi,
          _calApi,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set userId(String? _userId) => super.noSuchMethod(
        Invocation.setter(
          #userId,
          _userId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<String?> getAccountId() => (super.noSuchMethod(
        Invocation.method(
          #getAccountId,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<bool> trySilentGoogleSignIn() => (super.noSuchMethod(
        Invocation.method(
          #trySilentGoogleSignIn,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> signIn(
    dynamic email,
    dynamic signInMethod, {
    dynamic password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            email,
            signInMethod,
          ],
          {#password: password},
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> register(
    dynamic email,
    dynamic username,
    dynamic signInMethod, {
    dynamic password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            email,
            username,
            signInMethod,
          ],
          {#password: password},
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> checkStoredToken() => (super.noSuchMethod(
        Invocation.method(
          #checkStoredToken,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i12.Uint8List> cropToSquare(_i12.Uint8List? imageBytes) =>
      (super.noSuchMethod(
        Invocation.method(
          #cropToSquare,
          [imageBytes],
        ),
        returnValue: _i6.Future<_i12.Uint8List>.value(_i12.Uint8List(0)),
      ) as _i6.Future<_i12.Uint8List>);
}
