// Mocks generated by Mockito 5.4.4 from annotations
// in coordimate/test/components/agenda_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:coordimate/controllers/meeting_controller.dart' as _i3;
import 'package:coordimate/models/agenda_point.dart' as _i6;
import 'package:coordimate/models/meeting.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMeetingDetails_0 extends _i1.SmartFake
    implements _i2.MeetingDetails {
  _FakeMeetingDetails_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MeetingController].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeetingController extends _i1.Mock implements _i3.MeetingController {
  MockMeetingController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.MeetingDetails> fetchMeetingDetails(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMeetingDetails,
          [id],
        ),
        returnValue: _i4.Future<_i2.MeetingDetails>.value(_FakeMeetingDetails_0(
          this,
          Invocation.method(
            #fetchMeetingDetails,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.MeetingDetails>);

  @override
  _i4.Future<String> fetchMeetingSummary(dynamic id) => (super.noSuchMethod(
        Invocation.method(
          #fetchMeetingSummary,
          [id],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #fetchMeetingSummary,
            [id],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<bool> finishMeeting(dynamic id) => (super.noSuchMethod(
        Invocation.method(
          #finishMeeting,
          [id],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.MeetingStatus> answerInvitation(
    bool? accept,
    dynamic id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #answerInvitation,
          [
            accept,
            id,
          ],
        ),
        returnValue:
            _i4.Future<_i2.MeetingStatus>.value(_i2.MeetingStatus.declined),
      ) as _i4.Future<_i2.MeetingStatus>);

  @override
  _i4.Future<List<_i2.MeetingTileModel>> fetchArchivedMeetings() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchArchivedMeetings,
          [],
        ),
        returnValue: _i4.Future<List<_i2.MeetingTileModel>>.value(
            <_i2.MeetingTileModel>[]),
      ) as _i4.Future<List<_i2.MeetingTileModel>>);

  @override
  _i4.Future<void> saveSummary(
    dynamic id,
    dynamic summaryText,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSummary,
          [
            id,
            summaryText,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.AgendaPoint>> getAgendaPoints(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAgendaPoints,
          [id],
        ),
        returnValue:
            _i4.Future<List<_i6.AgendaPoint>>.value(<_i6.AgendaPoint>[]),
      ) as _i4.Future<List<_i6.AgendaPoint>>);

  @override
  _i4.Future<void> createAgendaPoint(
    dynamic id,
    String? text,
    int? level,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAgendaPoint,
          [
            id,
            text,
            level,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAgendaPoint(
    dynamic id,
    int? index,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAgendaPoint,
          [
            id,
            index,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateAgenda(
    dynamic id,
    dynamic agenda,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAgenda,
          [
            id,
            agenda,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.MeetingTileModel>> fetchMeetings() => (super.noSuchMethod(
        Invocation.method(
          #fetchMeetings,
          [],
        ),
        returnValue: _i4.Future<List<_i2.MeetingTileModel>>.value(
            <_i2.MeetingTileModel>[]),
      ) as _i4.Future<List<_i2.MeetingTileModel>>);

  @override
  _i4.Future<void> createMeeting(
    String? title,
    String? start,
    int? length,
    String? description,
    String? groupId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMeeting,
          [
            title,
            start,
            length,
            description,
            groupId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateMeetingTime(
    String? meetingId,
    String? start,
    int? duration,
    String? googleEventId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMeetingTime,
          [
            meetingId,
            start,
            duration,
            googleEventId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMeeting(
    String? meetingId,
    String? googleEventId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMeeting,
          [
            meetingId,
            googleEventId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> suggestMeetingLocation(String? meetingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #suggestMeetingLocation,
          [meetingId],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #suggestMeetingLocation,
            [meetingId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateMeetingLink(
    String? id,
    String? link,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMeetingLink,
          [
            id,
            link,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
