import 'package:flutter/material.dart';
import 'package:coordimate/components/draggable_bottom_sheet.dart';

const loginButtonKey = Key('loginButton');
const registerButtonKey = Key('registerButton');
const emailFieldKey = Key('email');
const passwordFieldKey = Key('password');
const confirmPasswordFieldKey = Key('confirmPassword');
const usernameFieldKey = Key('username');
const facebookTileKey = Key('facebookTile');
const googleTileKey = Key('googleTile');
const alertDialogKey = Key('alertDialog');
const okButtonKey = Key('okButton');
const calendarDayBoxKey = Key('calendarDayBox');
// final GlobalKey<DraggableBottomSheetState> draggableBottomSheetKey = GlobalKey<DraggableBottomSheetState>();
const draggableBottomSheetKey = Key('draggableBottomSheet');
const bottomNavigationBarKey = Key('bottomNavigationBar');
const scheduleNavigationButtonKey = Key('scheduleNavigation');
const meetingsNavigationButtonKey = Key('meetingsNavigation');
const groupsNavigationButtonKey = Key('groupsNavigation');
const archiveButtonKey = Key('archiveButton');
const meetingsScrollViewKey = Key('meetingCard');